### PR TITLE
Rewrite to not require privileged network interface access

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
Make the default to listen for UDP packages on port 4729 without
special privileges.  Use --sniff for old behaviour using scapy.sniff.

This require the latest version of grgsm_livemon in gr-gsm with
support for the --serverport option to make sure the port is available
for listening.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
You might want to remote the --sniff alternative, to simplify the code.

**Comment by Oros42** [comment]
We can keep the --snif.
If we haven't the last grgsm_livemon, we get this error :
```
Traceback (most recent call last):
  File "simple_IMSI-catchert2.py", line 510, in <module>
    udpserver(port=options.port, prn=find_imsi)
  File "simple_IMSI-catchert2.py", line 467, in udpserver
    sock.bind(server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
```
Did you think we can catch this error and print a message to tell to use --snif ?

Could you add your name to Contributors and update the README.md ?

**Comment by petterreinholdtsen** [comment]
[Oros42]
> We can keep the --snif.
> If we haven't the last grgsm_livemon, we get this error :

Yes.  Time to upgrade. :)

> Did you think we can catch this error and print a message to tell to
> use --snif ?

Sure.  Just add a try/catch block around bind (or the udpserver() call),
and print a suggestion about upgrading gr-gsm or run as root.

> Could you add your name to Contributors and update the README.md ?

Not quite sure what you have in mind.  Is there a particular reason why
you want me to do it, if you have an idea what should be in there?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by Oros42** [comment]
For the README.md, explain how to run it (case with --snif and case without --snif) and add the output of  ```python simple_IMSI-catcher.py -h```.

**Pull request merged**
