### PR TITLE
Added options save to txtfile, mysql and re-coded with flake8

### PR DESCRIPTION
**Pull request by purwowd**

### CODE REVIEW

**Comment by Oros42** [comment]
Could you :
- move ```.env``` to ```.env.dist```
```.env``` shouldn't be in git because it content user config.

- take care of case where MySQL is not setup. Call lines 29 to 37 only if ```.env``` exist
- line 221, if MySQL is not use don't print message

Thank

**Comment by purwowd** [comment]
@Oros42 Thanks for your guidance. I will resolve this issue ASAP.

**Comment by purwowd** [comment]
If you have time, please recheck my commit :D

**Comment by Oros42** [comment]
Thank :-)

**Pull request merged**
