### PR TITLE
fix 'brand' and 'country' mismatch in stdout header

### PR DESCRIPTION
**Pull request by brannondorsey**
"brand" and "country" are swapped in the table header.

### CODE REVIEW

**Comment by Oros42** [comment]
It's not this line who are wrong.

**Comment by brannondorsey** [comment]
Ah, should it instead keep the header order as it was but print the appropriate values in the correct place?

**Comment by Oros42** [comment]
It fixed in my last commit https://github.com/Oros42/IMSI-catcher/commit/4f091094258f5ccfa3f254ad784fc252bdc68dfc

**Comment by brannondorsey** [comment]
Great, thanks for the update!

**Pull request closed without merging**
